version: "3"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "7001:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    env_file: .env
    container_name: app
    volumes:
      - '.:/usr/src'
    build: .
    links:
      - database
    depends_on:
      - database
    ports:
      - "${PORT}:${PORT}"

volumes:
  db_data:
